### ISSUE TITLE
Collection object provided could not be reached

### ISSUE THREAD

**Issue by 4rchib4ld** [siriussecurity/mitre-attack-mapping#1]
Hello,

I've been trying to use your script, I've completed the `mitre-mapping.xlsx` file and installed the requirements. However, once I launch my script, I got this error : 
```
" Collection object provided could not be reached. Recieved error:", e,
stix2.datastore.DataSourceError: The underlying TAXII Collection resource defined in the supplied TAXII Collection object provided could not be reached. Recieved error: "406 Client Error: Not Acceptable for url: https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/"
```

Do you have an idea of how I can fix this ?
Thank you :)

**Comment by rubinatorz** [comment]
Hi @4rchib4ld 

Recently a new version of the taxii2-client python library was released: version 2.0.0. This library uses TAXII 2.1 classes by default, but this version is not supported by MITRE's TAXII server. So if you look at your installed python packages you will see that you have version 2.0.0 of the taxii2-client library. If you uninstall this version with "pip uninstall taxii2-client" and then install version 1.0.1 with "pip install taxii2-client==1.0.1" your problem will be solved. 

I will also add this dependency to the requirements.txt for future users.

This project is already a bit outdated, so you may want to look at the successor project:
https://github.com/rabobank-cdc/DeTTECT

Cheers,
Ruben
